---

#Terraform not in defaut package in *ubuntu20.04
- name: Add HashiCorp Terraform Apt signing key
  apt_key:
    url: "{{ hashicorp_apt_key_url }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add HashiCorp repository into sources list
  ansible.builtin.apt_repository:
    repo: "{{ hashicorp_repo_jammy }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Install Terraform Package
  package:
    name: "{{ terraform_client_tools }}"
    state: present

...
