---

- name: Install Messenging apps via snap
  community.general.snap:
    name: "{{ messengers_snaps }}"

#Cette version du paquet Snap "skype" a été publiée avec un confinement classique. Elle pourrait donc apporter des modifications arbitraires au système, au-delà de l'espace mémoire protégé (« sandbox ») dans lequel les paquets Snap sont généralement confinés, ce qui peut créer un risque pour votre système.
- name: Install Messenging apps via snap with classic option
  community.general.snap:
    name: "{{ messengers_snaps_classic }}"
    classic: yes

#MS Teams is not in defaut package in *ubuntu20.04
- name: Add Microsoft Apt signing key
  apt_key:
    url: "{{ messengers_teams_key_url }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add Microsoft Teams repository into sources list
  apt_repository:
    repo: "{{ messengers_teams_repo_url }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Install Messenger like Teams Packages
  package:
    name: "{{ messengers_packages }}"
    state: present
    
...
