---

- block:
  - name: add vscode apt key
    apt_key:
      url: "{{ vscode_apt_key }}"

  - name: add vscode repo
    apt_repository:
      repo: "{{ vscode_repo }}"
      state: present
      filename: vscode
  when: ansible_os_family == "Debian"

- name: install latest visual studio code
  package:
    name: code
    state: present

- name: install some popular vscode extensions
  command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  become_user: "{{ local_username }}"

...
