---

messengers_snaps_classic:
  - skype                                #One Skype for all your devices. New features. New look. All Skype.
  - slack                                #Signal Desktop

messengers_snaps:
  - signal-desktop                       #Signal Desktop
  - mattermost-desktop                   #Open source, private cloud Slack-alternative

messengers_packages:
  - teams                                #Microsoft Teams for Linux is your chat-centered workspace in Office 365.
  - telegram-desktop                     #fast and secure messaging application

messengers_teams_repo_url: "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main"

messengers_teams_key_url: "https://packages.microsoft.com/keys/microsoft.asc"

...
