---

- name: install privacy packages
  package:
    name: "{{ privacy_packages }}"
    state: present

- block:
    - name: copy torrc file
      copy:
        src: etc/tor/torrc
        dest: /etc/tor/torrc
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: ensure tor service runs on system startup
      service:
        name: tor
        state: started
        enabled: yes
  when: '"tor" in ansible_facts.packages'

- block:
    - name: copy proxychains4 config file
      copy:
        src: etc/proxychains4.conf
        dest: /etc/proxychains4.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes
  when: '"proxychains4" in ansible_facts.packages'

...
