---

#Atom not in defaut package in *ubuntu20.04
- name: Add Atom Apt signing key
  apt_key:
    url: "{{ atom_gpg_url }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add Atom repository into sources list
  apt_repository:
    repo: "{{ atom_repo }}"
    state: present
  when: ansible_os_family == "Debian"

##Only on *ubuntu18.04
#- name: Add PPA repository for ATOM editor
#  apt_repository:
#    repo: "ppa:webupd8team/atom"
#    state: present

- name: Install Atom Package
  package:
    name: "{{ atom_tools }}"
    state: present

- name: List modules on Atom Editor
  command: apm list -i
  register: atom_modules_installed

- name: Add modules on Atom Editor
  command : apm install {{ item }}
  with_items: "{{ atom_plugins }}"
  when: not atom_modules_installed.stdout | regex_search(item)

- name: Define Atom Editor for plain text files
  lineinfile:
    backup: yes
    path: /usr/share/applications/defaults.list
    regexp: '^text/plain=gedit.desktop'
    line: 'text/plain=atom.desktop'

...
